import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavigation from "@/components/SideNavigation";
import TopBar from "@/components/TopBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <div className="flex h-full">
               <SideNavigation />
               <div className="flex flex-col overflow-auto w-full h-full ">
                  <TopBar className="sticky top-0" />
                  {children}
               </div>
            </div>
         </body>
      </html>
   );
}
